print("This is my first line code")
print("This is my second line code")
print("This is my third line code")
print("This is my forth line code")
print("this is my fifth line code")
print("this is my sixth line code")
